//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SliderMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UserDetail
    {
        public long id { get; set; }
        [Required(ErrorMessage = "User Name Required")]
        [DisplayName("User Name")]
        public string User_Name { get; set; }
        [DisplayName("Full Name")]
        [Required(ErrorMessage = "Full Name Required")]
        public string full_name { get; set; }
        [DisplayName("Email Id")]
        [Required(ErrorMessage = "Email Id Required")]
        [EmailAddress(ErrorMessage = "Invalid Email")]
        public string email_id { get; set; }

        [DisplayName("Gender")]
        [Required(ErrorMessage = "Gender Required")]
        public string gender { get; set; }

        [DisplayName("Mobile No")]
        [Required(ErrorMessage = "Mobile No Required")]
        public string mobile_no { get; set; }


        [DisplayName("Password")]
        [DataType(DataType.Password)]

        [Required(ErrorMessage = "Password  Required")]
        public string password { get; set; }

        [DisplayName("Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("password", ErrorMessage = "Password Must Be Matched")]
        [Required(ErrorMessage = "Confirm Password Required")]
        public string confirmpassword { get; set; }
    }
}
